AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  AutoScheduler:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: arn:aws:iam::273354660155:role/AutoSchedulerExecutionRole  # Replace with your actual AWS account ID
      FunctionName: AutoScheduler
      MemorySize: 128
      Timeout: 300
      Runtime: python3.9
      Code:
        S3Bucket: my-bucket  # Replace with your S3 bucket name
        S3Key: my-function.zip  # Path to your Lambda function code
      Environment:
        Variables:
          ENV_VAR: value  # Example environment variable, adjust as needed

  SchedulerLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: arn:aws:iam::273354660155:role/SchedulerLambdaExecutionRole  # Replace with your actual AWS account ID
      FunctionName: SchedulerLambdaFunction
      MemorySize: 128
      Timeout: 300
      Runtime: python3.9
      Code:
        S3Bucket: my-bucket  # Replace with your S3 bucket name
        S3Key: scheduler-function.zip  # Path to your Lambda function code
      Environment:
        Variables:
          ENV_VAR: value  # Example environment variable, adjust as needed

Outputs:
  AutoSchedulerFunction:
    Description: "AutoScheduler Lambda Function ARN"
    Value: !GetAtt AutoScheduler.Arn

  SchedulerLambdaFunction:
    Description: "SchedulerLambdaFunction Lambda Function ARN"
    Value: !GetAtt SchedulerLambdaFunction.Arn
