version = 0.1
[default]
[default.build.parameters]
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-d9rreooialv5"
s3_prefix = "aws-sam-cli-managed-default-samclisourcebucket-d9rreooialv5"
region = "us-east-2"
[default.deploy]
[default.deploy.parameters]
s3_bucket = "laws-sam-cli-managed-default-samclisourcebucket-d9rreooialv5"
s3_prefix = "aws-sam-cli-managed-default-samclisourcebucket-d9rreooialv5"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
