REGION = 'us-east-1'


FROM_MAIL = 'support@zita.ai'

CONFIGTABLE = "CONFIGTABLE"
USERTABLE = "USERTABLE"
CLIENTPURCHASETABLE = "CLIENTPURCHASETABLE"
APITABLE = "APITABLE"
NOTIFICATIONTABLE = "NOTIFICATIONTABLE"
INVOICETABLE = "INVOICETABLE"
COUPONTABLE = "COUPONTABLE"
USERCOUPONTABLE = "USERCOUPONTABLE"
COUPONUSERSPECIFICTABLE="COUPONUSERSPECIFICTABLE"
ENV = "ENV"
COGNITO = "COGNITO" 
CLIENT = "CLIENT"
APIGATEWAY = "APIGATEWAY"
BUCKETNAME = "BUCKETNAME"

