name: Deploy Lambda with API Gateway using SAM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"  # Change to your region

      - name: Install dependencies for pyenv
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            make \
            build-essential \
            libssl-dev \
            zlib1g-dev \
            libbz2-dev \
            libreadline-dev \
            libsqlite3-dev \
            wget \
            curl \
            llvm \
            libncurses5-dev \
            libncursesw5-dev \
            xz-utils \
            tk-dev \
            libffi-dev \
            liblzma-dev \
            python3-openssl \
            git

      - name: Install pyenv
        run: |
          curl https://pyenv.run | bash
          echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> ~/.bashrc
          echo 'eval "$(pyenv init --path)"' >> ~/.bashrc
          echo 'eval "$(pyenv init -)"' >> ~/.bashrc
          source ~/.bashrc

      - name: Install Python 3.8 using pyenv
        run: |
          pyenv install 3.8.12
          pyenv global 3.8.12
          python --version  # Verify Python version

      - name: Install pip for Python 3.8
        run: |
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python get-pip.py
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt

      - name: SAM Build
        run: |
          sam build

      - name: SAM Deploy
        run: |
          sam deploy --no-confirm-changeset --stack-name my-sam-stack --capabilities CAPABILITY_IAM
