name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2  # Replace with your AWS region

    - name: Install dependencies
      run: |
        cd lambda  # Change to the directory containing package.json
        npm install  # Or any other package manager if you're using a different language

    - name: Zip Lambda function
      run: |
        cd lambda  # Change to the directory containing Lambda code
        zip -r function.zip .  # Make sure you zip all necessary files

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name my-lambda-function  # Replace with your Lambda function name
          --zip-file fileb://lambda/function.zip  # Path to the zip file after being created

    - name: Verify deployment
      run: |
        aws lambda get-function --function-name my-lambda-function
